export const types = {
  GET_JOBS_REQUEST: 'GET_JOBS_REQUEST',
  GET_JOBS_SUCCESS: 'GET_JOBS_SUCCESS',
  GET_JOBS_FAILURE: 'GET_JOBS_FAILURE',

  GET_JOBS_COUNT_REQUEST: 'GET_JOBS_COUNT_REQUEST',
  GET_JOBS_COUNT_SUCCESS: 'GET_JOBS_COUNT_SUCCESS',
  GET_JOBS_COUNT_FAILURE: 'GET_JOBS_COUNT_FAILURE',

  GET_LABELS_REQUEST: 'GET_LABELS_REQUEST',
  GET_LABELS_SUCCESS: 'GET_LABELS_SUCCESS',
  GET_LABELS_FAILURE: 'GET_LABELS_FAILURE',

  FILTER_JOBS_REQUEST: 'FILTER_JOBS_REQUEST',
  FILTER_JOBS_SUCCESS: 'FILTER_JOBS_SUCCESS',
  FILTER_JOBS_FAILURE: 'FILTER_JOBS_FAILURE',
};